/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsPocketKeyManagerIndexRouteImport } from './routes/apps/pocket-key-manager/index'
import { Route as AppsPocketKeyManagerTermsRouteImport } from './routes/apps/pocket-key-manager/terms'
import { Route as AppsPocketKeyManagerSupportRouteImport } from './routes/apps/pocket-key-manager/support'
import { Route as AppsPocketKeyManagerPrivacyRouteImport } from './routes/apps/pocket-key-manager/privacy'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPocketKeyManagerIndexRoute =
  AppsPocketKeyManagerIndexRouteImport.update({
    id: '/apps/pocket-key-manager/',
    path: '/apps/pocket-key-manager/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsPocketKeyManagerTermsRoute =
  AppsPocketKeyManagerTermsRouteImport.update({
    id: '/apps/pocket-key-manager/terms',
    path: '/apps/pocket-key-manager/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsPocketKeyManagerSupportRoute =
  AppsPocketKeyManagerSupportRouteImport.update({
    id: '/apps/pocket-key-manager/support',
    path: '/apps/pocket-key-manager/support',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsPocketKeyManagerPrivacyRoute =
  AppsPocketKeyManagerPrivacyRouteImport.update({
    id: '/apps/pocket-key-manager/privacy',
    path: '/apps/pocket-key-manager/privacy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/pocket-key-manager/privacy': typeof AppsPocketKeyManagerPrivacyRoute
  '/apps/pocket-key-manager/support': typeof AppsPocketKeyManagerSupportRoute
  '/apps/pocket-key-manager/terms': typeof AppsPocketKeyManagerTermsRoute
  '/apps/pocket-key-manager/': typeof AppsPocketKeyManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/apps': typeof AppsIndexRoute
  '/apps/pocket-key-manager/privacy': typeof AppsPocketKeyManagerPrivacyRoute
  '/apps/pocket-key-manager/support': typeof AppsPocketKeyManagerSupportRoute
  '/apps/pocket-key-manager/terms': typeof AppsPocketKeyManagerTermsRoute
  '/apps/pocket-key-manager': typeof AppsPocketKeyManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/pocket-key-manager/privacy': typeof AppsPocketKeyManagerPrivacyRoute
  '/apps/pocket-key-manager/support': typeof AppsPocketKeyManagerSupportRoute
  '/apps/pocket-key-manager/terms': typeof AppsPocketKeyManagerTermsRoute
  '/apps/pocket-key-manager/': typeof AppsPocketKeyManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/apps/'
    | '/apps/pocket-key-manager/privacy'
    | '/apps/pocket-key-manager/support'
    | '/apps/pocket-key-manager/terms'
    | '/apps/pocket-key-manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/apps'
    | '/apps/pocket-key-manager/privacy'
    | '/apps/pocket-key-manager/support'
    | '/apps/pocket-key-manager/terms'
    | '/apps/pocket-key-manager'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/apps/'
    | '/apps/pocket-key-manager/privacy'
    | '/apps/pocket-key-manager/support'
    | '/apps/pocket-key-manager/terms'
    | '/apps/pocket-key-manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AppsPocketKeyManagerPrivacyRoute: typeof AppsPocketKeyManagerPrivacyRoute
  AppsPocketKeyManagerSupportRoute: typeof AppsPocketKeyManagerSupportRoute
  AppsPocketKeyManagerTermsRoute: typeof AppsPocketKeyManagerTermsRoute
  AppsPocketKeyManagerIndexRoute: typeof AppsPocketKeyManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/pocket-key-manager/': {
      id: '/apps/pocket-key-manager/'
      path: '/apps/pocket-key-manager'
      fullPath: '/apps/pocket-key-manager/'
      preLoaderRoute: typeof AppsPocketKeyManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/pocket-key-manager/terms': {
      id: '/apps/pocket-key-manager/terms'
      path: '/apps/pocket-key-manager/terms'
      fullPath: '/apps/pocket-key-manager/terms'
      preLoaderRoute: typeof AppsPocketKeyManagerTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/pocket-key-manager/support': {
      id: '/apps/pocket-key-manager/support'
      path: '/apps/pocket-key-manager/support'
      fullPath: '/apps/pocket-key-manager/support'
      preLoaderRoute: typeof AppsPocketKeyManagerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/pocket-key-manager/privacy': {
      id: '/apps/pocket-key-manager/privacy'
      path: '/apps/pocket-key-manager/privacy'
      fullPath: '/apps/pocket-key-manager/privacy'
      preLoaderRoute: typeof AppsPocketKeyManagerPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AppsIndexRoute: AppsIndexRoute,
  AppsPocketKeyManagerPrivacyRoute: AppsPocketKeyManagerPrivacyRoute,
  AppsPocketKeyManagerSupportRoute: AppsPocketKeyManagerSupportRoute,
  AppsPocketKeyManagerTermsRoute: AppsPocketKeyManagerTermsRoute,
  AppsPocketKeyManagerIndexRoute: AppsPocketKeyManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
